### PR TITLE
Apply string util fixes

### LINKED ISSUE #182: Add Dan's fixes to string functions
See title. Tagging #180 .

### PR DESCRIPTION
**Pull request by cugone**
Applies changes recommended by @DanRStevens in PR #180 . I pulled latest on master before starting and for some reason gtest and gmock were not found when trying to build (Issue #184 ). Dunno how that happened.

Closes #182

### CODE REVIEW

File: src/Common.cpp [hunk 1]
```diff
@@ -177,13 +177,27 @@ std::vector<std::string> NAS2D::split(std::string str, char delim /*= ','*/, boo
 std::pair<std::string, std::string> NAS2D::splitOnFirst(const std::string& str, char delim)
 {
 	const auto delim_loc = str.find_first_of(delim);
-	return std::make_pair(str.substr(0, delim_loc), str.substr(delim_loc + 1));
+	if (delim_loc == std::string::npos)
+	{
+		return std::make_pair(std::string{}, str);
```
Comment (DanRStevens) [inline src/Common.cpp]: I feel like this may be backwards. If there is no delimiter, and so nothing to split on, I would expect the full string in the first return value, while the second value was empty.

File: src/Common.cpp [hunk 2]
```diff
@@ -177,13 +177,27 @@ std::vector<std::string> NAS2D::split(std::string str, char delim /*= ','*/, boo
...
+	}
 }
 
 std::pair<std::string, std::string> NAS2D::splitOnLast(const std::string& str, char delim)
 {
 	const auto delim_loc = str.find_last_of(delim);
-	return std::make_pair(str.substr(0, delim_loc), str.substr(delim_loc + 1));
+	if (delim_loc == std::string::npos)
+	{
+		return std::make_pair(str, std::string{});
```
Comment (DanRStevens) [inline src/Common.cpp]: This one also feels reversed to my expectations.

File: include/NAS2D/Common.h [hunk 3]
```diff
@@ -45,8 +46,8 @@ std::pair<std::string, std::string> splitOnLast(const std::string& str, char del
 std::string join(std::vector<std::string> strs, char delim, bool skip_empty = true);
 std::string join(std::vector<std::string> strs, bool skip_empty = true);
 std::string trimWhitespace(std::string string);
-bool startsWith(const std::string& string, const std::string& start) noexcept;
-bool endsWith(const std::string& string, const std::string& end) noexcept;
+bool startsWith(const std::string_view& string, const std::string& start) noexcept;
+bool endsWith(const std::string_view& string, const std::string& end) noexcept;
```
Comment (DanRStevens) [inline include/NAS2D/Common.h]: Ahh, excellent, I like this. That's true, this was added in C++17, which we're now using.

Comment (cugone) [reply include/NAS2D/Common.h]: Funny thing, when looking this up, I found that in C++20 there's going to be a `starts_with` and `ends_with` added to the standard library (that *only* operates on `string_view`s). So this is just a temporary work around until that gets implemented by at least MSVC. 

The string versions internally convert to a string_view:
https://en.cppreference.com/w/cpp/string/basic_string/starts_with
https://en.cppreference.com/w/cpp/string/basic_string/ends_with
https://en.cppreference.com/w/cpp/string/basic_string_view/starts_with
https://en.cppreference.com/w/cpp/string/basic_string_view/ends_with

File: src/Common.cpp (hunk 1 above)
Comment (cugone) [reply src/Common.cpp]: I intended it to be "wherever the rest of the string is". In this case "the rest of the string" is the whole string. Maybe a comment or documentation?

File: src/Common.cpp (hunk 2 above)
Comment (cugone) [reply src/Common.cpp]: Now I'm confused. You said the previous one felt backwards, yet this is the reverse of the previous and you're saying it's backwards too.

**Comment by cugone** [comment]
@DanRStevens 
@ldicker83 

Re-added string_view versions, both VS2017 and VS2019 support them.

File: include/NAS2D/Common.h (hunk 3 above)
Comment (DanRStevens) [reply include/NAS2D/Common.h]: A `string_view` should encompass read only access to all of the common string types. If an algorithm is designed to work with a `string_view`, it should work for any of the string types, be they `std::string`, or null terminated `char*` arrays. It's basically a `const char*` and a `size` field tied together. Very cheap to construct or pass by-value.

File: src/Common.cpp (hunk 1 above)
Comment (DanRStevens) [reply src/Common.cpp]:
```cpp
splitOnFirst(",abc", ',');  // { "", "abc" }
splitOnFirst("a,bc", ',');  // { "a", "bc" }
splitOnFirst("ab,c", ',');  // { "ab", "c" }
splitOnFirst("abc,", ',');  // { "abc", "" }
splitOnFirst("abc", ',');  // { "abc", "" }  <- Suggestion (rather than { "", "abc" })
```
If the first component is all the stuff before the delimiter, and there is no delimiter, I feel the first component should then be the whole string.

File: src/Common.cpp (hunk 2 above)
Comment (DanRStevens) [reply src/Common.cpp]:
```cpp
splitOnLast("abc,", ',');  // { "abc", "" }
splitOnLast("ab,c", ',');  // { "ab", "c" }
splitOnLast("a,bc", ',');  // { "a", "bc" }
splitOnLast(",abc", ',');  // { "", "abc" }
splitOnLast("abc", ',');  // { "", "abc" }  <- Suggestion (rather than { "abc", "" })
```

If the second component is all the stuff after the delimiter (scanning backwards), and there is no delimiter, I feel the second component should then be the whole string.

**Comment by DanRStevens** [comment]
Looks like the CI error was fixed on master. Changes look good.

Maybe give Leeor a chance to respond.

**Comment by cugone** [comment]
Yeah it's my intent to wait for approval from both of you. This change isn't a tiny one-liner like fixing the test project settings was.
