### PR TITLE
Fix Clang warnings

### LINKED ISSUE #244: Clang 8+ warnings - explicitly defaulted operations are implicitly deleted
Clang 8+ (tested with Clang 8, 9, 10) produces a new warning:
```
In file included from src/Mixer/MixerNull.cpp:1:
include/NAS2D/Mixer/MixerNull.h:12:3: warning: explicitly defaulted copy constructor is implicitly deleted [-Wdefaulted-function-deleted]
                MixerNull(const MixerNull& other) = default;
                ^
include/NAS2D/Mixer/MixerNull.h:8:20: note: copy constructor of 'MixerNull' is implicitly deleted because base class 'NAS2D::Mixer' has a deleted copy constructor
        class MixerNull : public Mixer
                          ^
include/NAS2D/Mixer/Mixer.h:171:2: note: 'Mixer' has been explicitly marked deleted here
        Mixer(const Mixer&) = delete;
        ^
In file included from src/Mixer/MixerNull.cpp:1:
include/NAS2D/Mixer/MixerNull.h:13:3: warning: explicitly defaulted move constructor is implicitly deleted [-Wdefaulted-function-deleted]
                MixerNull(MixerNull&& other) = default;
                ^
include/NAS2D/Mixer/MixerNull.h:8:20: note: move constructor of 'MixerNull' is implicitly deleted because base class 'NAS2D::Mixer' has a deleted move constructor
        class MixerNull : public Mixer
                          ^
include/NAS2D/Mixer/Mixer.h:171:2: note: 'Mixer' has been explicitly marked deleted here
        Mixer(const Mixer&) = delete;
        ^
In file included from src/Mixer/MixerNull.cpp:1:
include/NAS2D/Mixer/MixerNull.h:14:14: warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
                MixerNull& operator=(const MixerNull& other) = default;
                           ^
include/NAS2D/Mixer/MixerNull.h:8:20: note: copy assignment operator of 'MixerNull' is implicitly deleted because base class 'NAS2D::Mixer' has a deleted copy assignment operator
        class MixerNull : public Mixer
                          ^
include/NAS2D/Mixer/Mixer.h:172:9: note: 'operator=' has been explicitly marked deleted here
        Mixer& operator=(const Mixer&) = delete;
               ^
In file included from src/Mixer/MixerNull.cpp:1:
include/NAS2D/Mixer/MixerNull.h:15:14: warning: explicitly defaulted move assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
                MixerNull& operator=(MixerNull&& other) = default;
                           ^
include/NAS2D/Mixer/MixerNull.h:8:20: note: move assignment operator of 'MixerNull' is implicitly deleted because base class 'NAS2D::Mixer' has a deleted move assignment operator
        class MixerNull : public Mixer
                          ^
include/NAS2D/Mixer/Mixer.h:172:9: note: 'operator=' has been explicitly marked deleted here
        Mixer& operator=(const Mixer&) = delete;
               ^
4 warnings generated.
```

### PR DESCRIPTION
**Pull request by DanRStevens**
Closes #244

Fixes new Clang warnings concerning special member functions.

### CODE REVIEW

File: include/NAS2D/Mixer/MixerNull.h [hunk 1]
```diff
@@ -5,7 +5,7 @@
 namespace NAS2D
 {
 
-	class MixerNull : public Mixer
+	class MixerNull final : public Mixer
```
Comment (cugone) [inline include/NAS2D/Mixer/MixerNull.h]: I understand your reasons for marking this class `final` but carefully consider this decision. Refer to `C.139: Use final sparingly`: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-final

Comment (DanRStevens) [reply include/NAS2D/Mixer/MixerNull.h]: I would agree `final` shouldn't be overused. Here it seems justified, though whether or not it's necessary is another thing. I'm open to taking it out if we think it's a bad idea.

I suppose maybe we could end up writing something like a `MixerNullWithLogging`. And the potential slicing from misuse through a base class pointer seems pretty unlikely to happen, so it doesn't really protect from much.

I suspect this is the sort of thing you have better intuition about after making a mistake with it.
