### PR TITLE
Wrap calls to glGetString

### LINKED ISSUE #544: Possible crash bug in RendererOpenGL initialization
The function [`glGetString`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetString.xhtml) can potentially return 0, which can cause an access violation if it is dereferenced. This can happen during `RendererOpenGL` initialization in the `std::string` constructor:
```cpp
	// Spit out system graphics information.
	std::cout << "\t- OpenGL System Info -" << std::endl;

	driverName((char*)glGetString(GL_RENDERER));

	std::cout << "\tVendor: " << glGetString(GL_VENDOR) << std::endl;
	std::cout << "\tRenderer: " << driverName() << std::endl;
	std::cout << "\tDriver Version: " << glGetString(GL_VERSION) << std::endl;

	std::string glsl_v = (char*)glGetString(GL_SHADING_LANGUAGE_VERSION);
```

When running Windows in a virtual machine, the last line causes a crash.

----

Since we call `glGetString` multiple times, perhaps we should wrap it in a method that can safely return an empty `std::string` when a `nullptr` is returned.

### PR DESCRIPTION
**Pull request by DanRStevens**
Closes #544

Wraps call to `glGetString`, allowing for translation of `nullptr` results to an empty `std::string`. Previously the code would crash in the `std::string` constructor if `nullptr` result was returned.

### CODE REVIEW

File: src/Renderer/RendererOpenGL.cpp [hunk 1]
```diff
@@ -58,6 +58,13 @@ namespace {
 
 	GLfloat vertexArray[12] = {}; /**< Vertex array for quad drawing functions (all blitter functions). */
 	GLfloat textureCoordArray[12] = {}; /**< Texture coordinate array for quad drawing functions (all blitter functions). */
+
+
+	std::string glString(GLenum name)
+	{
+		const auto apiResult = glGetString(name);
+		return apiResult ? reinterpret_cast<const char*>(apiResult) : "";
```
Comment (cugone) [inline src/Renderer/RendererOpenGL.cpp]: Consider using braced initialization and moving the cast wrap the `glGetString` call:
```
const auto* apiResult = reinterpret_cast<const char*>(glGetString(name));
return { apiResult ? apiResult : "" };
```

Comment (DanRStevens) [reply src/Renderer/RendererOpenGL.cpp]: That looks fine. I'm curious though, is there a particular reason?

Comment (cugone) [reply src/Renderer/RendererOpenGL.cpp]: RVO gets invoked instead of a construct-then-copy/move. Makes it so there's no move and no copy in the first place.

Comment (DanRStevens) [reply src/Renderer/RendererOpenGL.cpp]: I'm not quite sure I follow. It should be the same either way? The `const char*` is used to construct a `std::string`. As that `std::string` is being directly returned RVO should apply.

Comment (cugone) [reply src/Renderer/RendererOpenGL.cpp]: Copy elision versus RVO. six of one, half-a-dozen of the other. :P

Comment (DanRStevens) [reply src/Renderer/RendererOpenGL.cpp]: Add obligatory reference to [copy elision](https://en.cppreference.com/w/cpp/language/copy_elision) (which also talks about RVO and NRVO).

Comment (DanRStevens) [reply src/Renderer/RendererOpenGL.cpp]: So where do we stand on this now? The suggestions seem largely about style. I can't think of any technical reason for the change.

----

I think I would prefer leaving the cast where it is. It makes more sense to me to catch the raw API type/value as is. In some cases (not applicable here) if you were to interact further with an API, you would want values still in the original data type. Converting data (even if there is no actual runtime cost) seems like it should be done only when absolutely necessary.

----

The braces I could go either way on. They don't seem to do anything, so I'm a bit inclined to leave them off, though you could potentially make a case for readability or style here. Certainly they would be used when constructing `struct` return values.

Comment (cugone) [reply src/Renderer/RendererOpenGL.cpp]: All I ask is the optioned be considered. Having done that...
